info:
name: Update task
type: http
seq: 5

http:
method: PUT
url: http://127.0.0.1:8000/tasks/1
headers:
- name: Content-Type
value: application/json
auth: inherit
body:
type: json
data: |-
{
"title": "Tâche mise à jour",
"priority": "medium"
}

runtime:
scripts:
- type: tests
code: |-
test("Modification de tâche", function() {
expect(res.status).to.equal(200);
expect(res.body.title).to.equal("Tâche mise à jour");
});

settings:
encodeUrl: true
timeout: 0
followRedirects: true
maxRedirects: 5
